version: '1'
run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - deadcode
    - typecheck
    - varcheck
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 